 version:  "3.8"

 services: 
  backendimg:
    build: /root/DockerImage_studentapp_threetier/Backend/
    container_name : backend
    ports: 
       - 8080:8080
    depends_on:
      - frontendimg
  frontendimg:  
    build:  /root/DockerImage_studentapp_threetier/Frontend/
    container_name: frontend
    ports: 
       - 80:80
   